name: diffusion-detective
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - cudatoolkit=11.8
  - numpy
  - pillow
  - pip:
    - --upgrade pip
    - diffusers[torch]
    - transformers
    - accelerate
    - safetensors
    - bitsandbytes
    - gradio
    - ftfy
    - einops
    - datasets
    - lpips
    - tokenizers
    - huggingface_hub
    - git+https://github.com/openai/CLIP.git
    - omegaconf
    - wandb
